=== cismet/report-api/src/main/resources/de/cismet/projecttracker/report/commons/holidayConfig.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://cismet.de/projecttracker/report/commons/holidayConfig"
    xmlns:hc="http://cismet.de/projecttracker/report/commons/holidayConfig"
    elementFormDefault="qualified">

    <xsd:element name="holidayConfig" type="hc:HolidayConfig" />

    <xsd:complexType name="HolidayConfig">
        <xsd:sequence>
            <xsd:element name="holiday" maxOccurs="unbounded">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="name" type="xsd:string" />
                        <xsd:element name="isHalfHoliday" type="xsd:boolean" />
                        <xsd:element name="time" type="hc:Time" />
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="Time">
        <xsd:choice>
            <xsd:element name="fixDate" type="hc:FixDate" />
            <xsd:element name="dayAfterEaster" type="xsd:integer" />
        </xsd:choice>
    </xsd:complexType>

    <xsd:complexType name="FixDate">
        <xsd:sequence>
            <xsd:element name="date" type="xsd:date" />
            <xsd:element name="isEveryYear" type="xsd:boolean" />
        </xsd:sequence>
    </xsd:complexType>

</xsd:schema>

=== cismet/report-api/src/main/resources/de/cismet/projecttracker/report/commons/holidayConfig.xml
<?xml version="1.0" encoding="UTF-8"?>

<hc:holidayConfig  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
   xmlns:hc='http://cismet.de/projecttracker/report/commons/holidayConfig'
   xsi:schemaLocation='http://cismet.de/projecttracker/report/commons/holidayConfig holidayConfig.xsd'>
    <hc:holiday>
        <hc:name>Neujahr</hc:name>
        <hc:isHalfHoliday>false</hc:isHalfHoliday>
        <hc:time>
            <hc:fixDate>
                <hc:date>2009-01-01</hc:date>
                <hc:isEveryYear>true</hc:isEveryYear>
            </hc:fixDate>
        </hc:time>
    </hc:holiday>
    <hc:holiday>
        <hc:name>Karfreitag</hc:name>
        <hc:isHalfHoliday>false</hc:isHalfHoliday>
        <hc:time>
            <hc:dayAfterEaster>-2</hc:dayAfterEaster>
        </hc:time>
    </hc:holiday>
    <hc:holiday>
        <hc:name>Ostermontag</hc:name>
        <hc:isHalfHoliday>false</hc:isHalfHoliday>
        <hc:time>
            <hc:dayAfterEaster>1</hc:dayAfterEaster>
        </hc:time>
    </hc:holiday>
    <hc:holiday>
        <hc:name>Maifeiertag</hc:name>
        <hc:isHalfHoliday>false</hc:isHalfHoliday>
        <hc:time>
            <hc:fixDate>
                <hc:date>2009-05-01</hc:date>
                <hc:isEveryYear>true</hc:isEveryYear>
            </hc:fixDate>
        </hc:time>
    </hc:holiday>
    <hc:holiday>
        <hc:name>Christi Himmelfahrt</hc:name>
        <hc:isHalfHoliday>false</hc:isHalfHoliday>
        <hc:time>
            <hc:dayAfterEaster>39</hc:dayAfterEaster>
        </hc:time>
    </hc:holiday>
    <hc:holiday>
        <hc:name>Pfingstmontag</hc:name>
        <hc:isHalfHoliday>false</hc:isHalfHoliday>
        <hc:time>
            <hc:dayAfterEaster>50</hc:dayAfterEaster>
        </hc:time>
    </hc:holiday>
    <hc:holiday>
        <hc:name>Fronleichnam</hc:name>
        <hc:isHalfHoliday>false</hc:isHalfHoliday>
        <hc:time>
            <hc:dayAfterEaster>60</hc:dayAfterEaster>
        </hc:time>
    </hc:holiday>
    <hc:holiday>
        <hc:name>Maria Himmelfahrt</hc:name>
        <hc:isHalfHoliday>false</hc:isHalfHoliday>
        <hc:time>
            <hc:fixDate>
                <hc:date>2009-08-15</hc:date>
                <hc:isEveryYear>true</hc:isEveryYear>
            </hc:fixDate>
        </hc:time>
    </hc:holiday>
    <hc:holiday>
        <hc:name>Tag der deutschen Einheit</hc:name>
        <hc:isHalfHoliday>false</hc:isHalfHoliday>
        <hc:time>
            <hc:fixDate>
                <hc:date>2009-10-03</hc:date>
                <hc:isEveryYear>true</hc:isEveryYear>
            </hc:fixDate>
        </hc:time>
    </hc:holiday>
    <hc:holiday>
        <hc:name>Allerheiligen</hc:name>
        <hc:isHalfHoliday>false</hc:isHalfHoliday>
        <hc:time>
            <hc:fixDate>
                <hc:date>2009-11-01</hc:date>
                <hc:isEveryYear>true</hc:isEveryYear>
            </hc:fixDate>
        </hc:time>
    </hc:holiday>
    <hc:holiday>
        <hc:name>1.Weihnachtsfeiertag</hc:name>
        <hc:isHalfHoliday>false</hc:isHalfHoliday>
        <hc:time>
            <hc:fixDate>
                <hc:date>2009-12-25</hc:date>
                <hc:isEveryYear>true</hc:isEveryYear>
            </hc:fixDate>
        </hc:time>
    </hc:holiday>
    <hc:holiday>
        <hc:name>2.Weihnachtsfeiertag</hc:name>
        <hc:isHalfHoliday>false</hc:isHalfHoliday>
        <hc:time>
            <hc:fixDate>
                <hc:date>2009-12-26</hc:date>
                <hc:isEveryYear>true</hc:isEveryYear>
            </hc:fixDate>
        </hc:time>
    </hc:holiday>
    <hc:holiday>
        <hc:name>Heiligabend</hc:name>
        <hc:isHalfHoliday>true</hc:isHalfHoliday>
        <hc:time>
            <hc:fixDate>
                <hc:date>2009-12-24</hc:date>
                <hc:isEveryYear>true</hc:isEveryYear>
            </hc:fixDate>
        </hc:time>
    </hc:holiday>
    <hc:holiday>
        <hc:name>Sylvester</hc:name>
        <hc:isHalfHoliday>true</hc:isHalfHoliday>
        <hc:time>
            <hc:fixDate>
                <hc:date>2009-12-31</hc:date>
                <hc:isEveryYear>true</hc:isEveryYear>
            </hc:fixDate>
        </hc:time>
    </hc:holiday>
    <hc:holiday>
        <hc:name>Reformationstag</hc:name>
        <hc:isHalfHoliday>false</hc:isHalfHoliday>
        <hc:time>
            <hc:fixDate>
                <hc:date>2017-10-31</hc:date>
                <hc:isEveryYear>false</hc:isEveryYear>
            </hc:fixDate>
        </hc:time>
    </hc:holiday>

</hc:holidayConfig>
